Medidores:
    type:     rest
    prefix:   /gestion
    resource: Sistema\ColegioBundle\Controller\GestionController

Cursos:
    type:     rest
    prefix:   /cursos
    resource: Sistema\ColegioBundle\Controller\CursosController

Estudiantes:
    type:     rest
    prefix:   /estudiantes
    resource: Sistema\ColegioBundle\Controller\EstudiantesController