Medidores:
    type:     rest
    prefix:   /gestion
    resource: Sistema\ColegioBundle\Controller\GestionController

Cursos:
    type:     rest
    prefix:   /cursos
    resource: Sistema\ColegioBundle\Controller\CursosController

Estudiantes:
    type:     rest
    resource: Sistema\ColegioBundle\Controller\EstudiantesController

Dispositivos:
    type:     rest
    resource: Sistema\ColegioBundle\Controller\DispositivosController

Reuniones:
    type:     rest
    resource: Sistema\ColegioBundle\Controller\ReunionesController

Profesores:
    type:     rest
    resource: Sistema\ColegioBundle\Controller\ProfesoresController

Notificaciones:
    type:     rest
    resource: Sistema\ColegioBundle\Controller\NotificacionesController