<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * CursosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursosRepository extends BaseRepository
{
}
