<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * CursoEvalDimActividadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursoEvalDimActividadRepository extends \Doctrine\ORM\EntityRepository
{
}
