<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * CursoEvalDimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursoEvalDimRepository extends BaseRepository
{
}
