<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * CursoMateriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursoMateriaRepository extends BaseRepository
{
}
