<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * DimensionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DimensionesRepository extends BaseRepository
{
}
