<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * DispositivosUsuariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DispositivosUsuariosRepository extends BaseRepository
{
}
