<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * DispositivosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DispositivosRepository extends BaseRepository
{
    public function obtenerAplicacion($sha)
    {
        $dispositivos = $this->findBy(array("estado" => 1));
        foreach ($dispositivos as $dispositivo) {
            $encrypt = sha1($dispositivo->getImei());
            if ($encrypt == $sha) {
                return $dispositivo;
            }
        }
        return null;
    }
}
