<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * EstudiantesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudiantesRepository extends BaseRepository
{
    /**
     * @param \Doctrine\ORM\Query|\Doctrine\ORM\QueryBuilder $query
     * @param $iddispositivo
     * @return \Doctrine\ORM\Query|\Doctrine\ORM\QueryBuilder
     */
    public function filtrarPorDispositivos($query, $iddispositivo)
    {
        $alias = $query->getRootAlias();
        $query->innerJoin($alias . '.dispositivosUsuarios', 'a');
        $query->andWhere('a.iddispositivo = :iddispositivo');
        $query->setParameter("iddispositivo", $iddispositivo);
        return $query;

    }
}
