<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * EstudiantesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudiantesRepository extends BaseRepository
{
}
