<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * GesCursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GesCursoRepository extends \Doctrine\ORM\EntityRepository
{
}
