<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * GestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GestionRepository extends BaseRepository
{
    public function obtenerGestionActual()
    {
        //TODO Implementar la consulta para obtener la gestion con estado = 0
        return 2016;
    }
}
