<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * GestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GestionRepository extends BaseRepository
{
}
