<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * KeyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeyRepository extends BaseRepository
{
}
