<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * MaestrosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaestrosRepository extends BaseRepository
{

    
}
