<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * MateriasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MateriasRepository extends BaseRepository
{
}
