<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * NotifEstudianteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotifEstudianteRepository extends BaseRepository
{
}
