<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * NotificacionesEstudianteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificacionesEstudianteRepository extends BaseRepository
{
}
