<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * NotificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificacionRepository extends BaseRepository
{
}
