<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * PeriodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodoRepository extends BaseRepository
{
}
