<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * PeriodoEvalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodoEvalRepository extends BaseRepository
{
}
