<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * ReunionMaestroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReunionMaestroRepository extends BaseRepository
{
}
