<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * TipoNotificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoNotificacionRepository extends BaseRepository
{
}
