<?php

namespace Sistema\ColegioBundle\Repository;

/**
 * UsuarioAppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioAppRepository extends BaseRepository
{
}
